# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 08:47
from __future__ import unicode_literals

import GoGarage.base_model
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('nick', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=150)),
                ('registrationNumber', models.CharField(max_length=150)),
                ('chassisNumber', models.CharField(blank=True, max_length=150, null=True)),
                ('manufacturedDate', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('image', models.ImageField(upload_to=GoGarage.base_model.vehicle_directory_path)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Vehicle.Vehicle')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vehicleimage',
            unique_together=set([('vehicle', 'image')]),
        ),
    ]
